# Generated by Django 5.0.4 on 2024-05-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Circle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[("B", "Black"), ("W", "White")], max_length=1
                    ),
                ),
                ("x", models.IntegerField()),
                ("y", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="GameBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("size", models.IntegerField()),
                ("circles", models.ManyToManyField(to="Masyu_Game.circle")),
            ],
        ),
    ]
